name: Deploy to GitHub Pages


on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Build Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docfx_project/docfx.json
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          clean: true
          folder: docs 